version: '3'

requires:
  vars:
    - DATASET # The path to the dataset available at https://doi.org/10.14459/2026mp1856124
    - RESULTS # Results (plots, etc.) are written to this folder
dotenv: [.env]

tasks:
  # --- Python utilities ---
  check-vars:
    internal: true
    requires:
      vars: [DATASET, RESULTS]
    preconditions:
      - sh: test -d '{{.DATASET}}'
        msg: 'DATASET folder "{{.DATASET}}" does not exist'
    cmds:
      - mkdir -p '{{.RESULTS}}'
    silent: true

  # --- Process TCP measurements ---
  process-tcp:*:
    desc: |
      Process NetScalpel TCP measurements with match-pcaps; expects a top-level
      directory which is filtered for {{.INFO_FILE}} files to process.
    vars:
      DIR: '{{index .MATCH 0}}'
      LOG: "{{.DIR}}/{{.TASK}}.log"
      INFO_FILE: '{{.INFO_FILE | default "info.txt"}}'
    cmds:
      - find "{{.DIR}}" -iname {{.INFO_FILE}} -print0 | parallel -0 --bar --group --joblog "{{.LOG}}" bash "tcp/pcap-match-tcp.sh" "{}"

  # --- Figures ---

  fig-02:
    desc: "Generate Figure 2."
    cmds:
      - task: check-vars
      # headdrop.pickle is needed by netns-drop figure
      - python3 figures/fig-02-headdrop.py '{{.DATASET}}'/multidurrate_1s/*multidurrate*/rate_{dl_500,ul_140}_1000.csv --pickle '{{.RESULTS}}/headdrop.pickle' -o '{{.RESULTS}}/fig-02.pdf'

  fig-03:
    desc: "Generate Figure 3."
    cmds:
      - task: check-vars
      - python3 figures/fig-03-bursts.py '{{.DATASET}}'/burst/*burst_{dl,ul}/burst_*_*_*.csv -o '{{.RESULTS}}/fig-03-bursts.pdf'

  fig-04:
    desc: "Generate Figure 4."
    cmds:
      - task: check-vars
      - python3 figures/fig-04-netns-drop.py '{{.DATASET}}'/netns/{head-drop-ul,tail-drop-ul,head-drop-dl,tail-drop-dl}.csv '{{.RESULTS}}/headdrop.pickle' -o '{{.RESULTS}}/fig-04.pdf'
    preconditions:
      - sh: test -f '{{.RESULTS}}/headdrop.pickle'
        msg: 'fig-04 depends on headdrop.pickle that is produced by fig-02: run task fig-02 first'

  fig-05:
    desc: "Generate Figure 5."
    cmds:
      - task: check-vars
      - python3 figures/fig-05-08-rampup.py  '{{.DATASET}}'/multidurrate_4s/*/rate_*{050,100,dl_200,300,400,dl_500,015,030,050,070,090,140}_*.csv -o '{{.RESULTS}}/fig-05-rampup.pdf'

  fig-06:
    desc: "Generate Figure 6."
    cmds:
      - task: check-vars
      - python3 figures/fig-06-cooldown.py sf '{{.DATASET}}'/cooldown_highrate/*/rate*csv -o '{{.RESULTS}}/fig-06-cooldown.pdf'

  fig-16:
    desc: "Generate Figure 16."
    cmds:
      - task: check-vars
      - python3 figures/fig-06-cooldown.py sf '{{.DATASET}}'/cooldown_lowrate/*/rate*csv -o '{{.RESULTS}}/fig-16-cooldown.pdf'

  fig-07-14:
    desc: "Generate Figure 7."
    cmds:
      - task: check-vars
      - python3 figures/fig-07-14-aqm.py '{{.RESULTS}}'/aqm-input.parquet -o '{{.RESULTS}}/fig-07-14-aqm.pdf'
    preconditions:
      - sh: test -f '{{.RESULTS}}/aqm-input.parquet'
        msg: 'fig-07-14 depends on aqm-input.parquet that is produced by aqm-input: first run task aqm-input'

  aqm-input:
    desc: "Generate data for fig-07-aqm"
    cmds:
      - task: check-vars
      - python3 figures/aqm-input.py -o '{{.RESULTS}}'/aqm-input.parquet '{{.DATASET}}'/multidurrate_4s/*/rate*_4000.csv '{{.DATASET}}'/tcp/*/tcp*packets.csv

  aqm-input-satpipe:
    desc: "Generate data for fig-07-aqm with the tcp-satpipe data"
    cmds:
      - task: check-vars
      - python3 figures/aqm-input.py -o '{{.RESULTS}}'/aqm-input-satpipe.parquet '{{.DATASET}}'/multidurrate_4s/*/rate*_4000.csv '{{.DATASET}}'/tcp-satpipe/*/tcp*packets.csv
    
  fig-08:
    desc: "Generate Figure 8."
    cmds:
      - task: check-vars
      - python3 figures/fig-05-08-rampup.py --xlim 1200 '{{.DATASET}}'/multidurrate_4s/*/rate_dl_{500,600,700}_*.csv -o '{{.RESULTS}}/fig-08-rampup-outlier.pdf'

  fig-09-rateri:
    desc: "Generate Figure 9 (rateri)."
    cmds:
      - task: check-vars
      - python3 figures/fig-09-rateri.py --sats '{{.DATASET}}/sats_2026-02-02/sats.csv' -o '{{.RESULTS}}/fig-09-rateri.pdf' -- '{{.DATASET}}'/rate/*/rate_{ul,dl}.csv

  fig-09-rate:
    desc: "Generate Figure 9 (rate)."
    cmds:
      - task: check-vars
      - python3 figures/fig-09-rate.py --sats '{{.DATASET}}/sats_2026-02-02/sats.csv' -o '{{.RESULTS}}/fig-09-rate.pdf' -- '{{.DATASET}}'/rate/*/rate_{ul,dl}.csv

  fig-10-15:
    desc: "Generate Figure 10 and 15."
    cmds:
      - task: check-vars
      - python3 figures/fig-10-15-mouseeleph.py plot '{{.DATASET}}'/{mouseeleph_ul,mouseeleph_dl_250}/*/*csv -o '{{.RESULTS}}/fig-10-15-mouseeleph.pdf'

  fig-10-15-stat:
    desc: "Run significance tests."
    cmds:
      - task: check-vars
      - python3 figures/fig-10-15-mouseeleph.py stat '{{.DATASET}}'/{mouseeleph_ul,mouseeleph_dl_250}/*/*csv -o '{{.RESULTS}}/fig-10-15-stat.txt'

  fig-11:
    desc: "Generate Figure 11."
    cmds:
      - task: check-vars
      - python3 figures/fig-11-tcpss.py '{{.DATASET}}'/tcp-satpipe/*/tcp_{dl,ul}_*_12000.csv -o '{{.RESULTS}}/fig-11-tcpss.pdf'

  fig-12:
    desc: "Generate Figure 12."
    cmds:
      - task: check-vars
      - python3 figures/fig-12-tcpri.py '{{.DATASET}}'/tcp-satpipe/*/{tcp,udp}_{dl,ul}_*_12000.*csv -o '{{.RESULTS}}/fig-12-tcpri.pdf'

  tcp-stat:
    desc: "Run TCP significance tests"
    cmds:
      - task: check-vars
      - python3 figures/tcp-stat.py '{{.DATASET}}'/tcp-satpipe/*/{tcp,udp}_{dl,ul}_*_12000.csv -o '{{.RESULTS}}/tcp-stat.txt' -p '{{.RESULTS}}/tcp-stat.pdf'
  tcp-stat-jan:
    desc: "Run TCP significance tests"
    cmds:
      - task: check-vars
      - python3 figures/tcp-stat.py '{{.DATASET}}'/tcp/*/{tcp,udp}_{dl,ul}_*_12000.csv -o '{{.RESULTS}}/tcp-stat-jan.txt' -p '{{.RESULTS}}/tcp-stat-jan.pdf'

  tcp-metrics:
    desc: "Gather TCP metrics"
    cmds:
      - task: check-vars
      - python3 figures/tcp-metrics.py -g tcp '{{.DATASET}}'/tcp-satpipe/*/tcp_{dl,ul}_*_12000.csv -o '{{.RESULTS}}/tcp-metrics.txt'
  tcp-metrics-jan:
    desc: "Gather TCP metrics"
    cmds:
      - task: check-vars
      - python3 figures/tcp-metrics.py -g tcp '{{.DATASET}}'/tcp/*/tcp_{dl,ul}_*_12000.csv -o '{{.RESULTS}}/tcp-metrics-jan.txt'
    
  fig-13:
    desc: "Generate Figure 13."
    cmds:
      - task: check-vars
      - python3 figures/fig-13-switchflow.py '{{.DATASET}}'/switchflow/*/rate_{ul,dl}_{0200,0300,0700,0020,0040,0070}_*.csv -o '{{.RESULTS}}/fig-13-switchflow.pdf'

  fig-18-owd:
    desc: "Generate Figure 18 (OWD)."
    cmds:
      - task: check-vars
      - python3 figures/fig-18-owd.py --sats '{{.DATASET}}/sats_2026-01-11/sats.csv' -o '{{.RESULTS}}/fig-18-owd-udp.pdf' -- '{{.DATASET}}'/owd/*/owd-udp_{ul,dl}.csv

  fig-18-idle:
    desc: "Generate Figure 18 (idle)."
    cmds:
      - task: check-vars
      - python3 figures/fig-18-loss.py -o '{{.RESULTS}}/fig-18-loss-idle.pdf' -- '{{.DATASET}}'/owd/*/owd-udp_{ul,dl}.csv




  # --- Data from other nodes ---

  fig-10-15-vic:
    desc: "Generate Figure 10 and 15."
    cmds:
      - task: check-vars
      - python3 figures/fig-10-15-mouseeleph.py plot '{{.DATASET}}'/vic/*mouseeleph*/*csv -o '{{.RESULTS}}/fig-10-15-mouseeleph-vic.pdf'

  fig-09-rateri-vic:
    desc: "Generate Figure 9 (rateri)."
    cmds:
      - task: check-vars
      - python3 figures/fig-09-rateri.py -o '{{.RESULTS}}/fig-09-rateri-vic.pdf' -- '{{.DATASET}}'/vic/*_rate_*/rate_{ul,dl}.csv

  fig-09-rate-vic:
    desc: "Generate Figure 9 (rate)."
    cmds:
      - task: check-vars
      - python3 figures/fig-09-rate.py -o '{{.RESULTS}}/fig-09-rate-vic.pdf' -- '{{.DATASET}}'/vic/*_rate_*/rate_{ul,dl}.csv

  fig-03-vic:
    desc: "Generate Figure 3."
    cmds:
      - task: check-vars
      - python3 figures/fig-03-bursts.py '{{.DATASET}}'/vic/*burst_{dl,ul}/burst_*_*_*.csv -o '{{.RESULTS}}/fig-03-bursts-vic.pdf'

  fig-06-vic:
    desc: "Generate Figure 6."
    # TODO: Refactor? Remove non-sf functionality?
    cmds:
      - task: check-vars
      - python3 figures/fig-06-cooldown.py sf '{{.DATASET}}'/vic/*cdsf*/rate*csv -o '{{.RESULTS}}/fig-06-cooldown-vic.pdf'

  fig-02-wat:
    desc: "Generate Figure 2."
    cmds:
      - task: check-vars
      # headdrop.pickle is needed by netns-drop figure
      - python3 figures/fig-02-headdrop.py '{{.DATASET}}'/wat/multidurrate/*multidurrate*/rate_{dl_500,ul_140}_1000.csv --pickle '{{.RESULTS}}/headdrop_wat.pickle' -o '{{.RESULTS}}/fig-02-wat.pdf'

  fig-05-wat:
    desc: "Generate Figure 5."
    cmds:
      - task: check-vars
      - python3 figures/fig-05-08-rampup.py  '{{.DATASET}}'/wat/multidurrate/*/rate_*_1500.csv -o '{{.RESULTS}}/fig-05-rampup-wat.pdf'
  
  fig-08-wat:
    desc: "Generate Figure 8."
    cmds:
      - task: check-vars
      - python3 figures/fig-05-08-rampup.py  '{{.DATASET}}'/wat/multidurrate/*/rate_dl_{300,500,700}_1500.csv -o '{{.RESULTS}}/fig-08-rampup-outlier-wat.pdf'
  
  fig-18-owd-wat:
    desc: "Generate Figure 18 (OWD)."
    cmds:
      - task: check-vars
      - python3 figures/fig-18-owd.py -o '{{.RESULTS}}/fig-18-owd-udp-wat.pdf' -- '{{.DATASET}}'/wat/owd/*/owd-udp_{ul,dl}.csv

  fig-18-idle-wat:
    desc: "Generate Figure 18 (idle)."
    cmds:
      - task: check-vars
      - python3 figures/fig-18-loss.py -o '{{.RESULTS}}/fig-18-loss-idle-wat.pdf' -- '{{.DATASET}}'/wat/owd/*/owd-udp_{ul,dl}.csv
